// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SkipTitleScreen","status":true,"description":"v1.00 Skips Title Screen\r\n<SilverSkipTitle>","parameters":{"Skip Title Screen Entirely":"true","Skip If Savefile Present":"true","FadeOut Title":"false"}}
];
